DEFRA/adp-infrastructure-services

README.md

Initial DOCUMENTATION FOR SERVICES INFRA
Supports PR: https://github.com/DEFRA/adp-infrastructure-services/pull/1
[![Build Status](https://dev.azure.com/defragovuk/DEFRA-FFC/_apis/build/status%2FADP%2FServices%2Fadp-ffc-services-infra?repoName=DEFRA%2Fadp-infrastructure-services&branchName=refs%2Fpull%2F1%2Fmerge)](https://dev.azure.com/defragovuk/DEFRA-FFC/_build/latest?definitionId=5056&repoName=DEFRA%2Fadp-infrastructure-services&branchName=refs%2Fpull%2F1%2Fmerge)

231044: Add Infra-services documentation

---

infra/bicep-generic/cdn/application-domain.main.bicep

Fixed path name case issue for the security policy module. 
[AB#249140](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249140)

249140:Fixed security policy path case issue

---

infra/services/ffc/deploy-services-infra.yaml
infra/services/ffc/ffc-ffd-frontend-poc/application-domain-custom-envs.yaml
infra/services/ffc/ffc-ffd-frontend-poc/application-domain.main.bicepparam

Added ffc-ffd-frontend-poc to allow for creation of Frontdoor configuration
[AB#284752](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/284752)

284752: Update adp-infrastructure-services to include ffc-ffd-frontend-poc

---

infra/services/eutd/deploy-services-infra.yaml
infra/services/eutd/trade-exports-packinglistai-ui/application-domain-custom-envs.yaml
infra/services/eutd/trade-exports-packinglistai-ui/application-domain.main.bicepparam

This PR contains the code changes for adding a new Delivery Programme level pipeline for onboarding microservices for that programme. The pipeline is used to configure AFD endpoints for public facing endpoints e.g: Relates to ADO Work Item [AB#259885](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259885) and builds on #5675 (https://dev.azure.com/defragovuk/DEFRA-FFC/_build?definitionId=5675)*

259885: Added pipeline changes for eutd programme

---

infra/bicep-generic/cdn/.bicep/route/main.bicep
infra/bicep-generic/cdn/application-domain.main.bicep
infra/services/ffc/ffc-demo-web/application-domain.main.bicepparam

Linking of globalRuleSets to all the routes.
Relates to ADO Work Item [AB#287384](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/287384)

287384: Link Global rule sets to the routes

---

infra/services/adp/portal/application-domain.main.bicepparam

Update the AFD endpoint for the portal.
Relates to ADO Work Item [AB#296203](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296203)
N/A
N/A

Update the AFD endpoint for the portal

---

.azuredevops/templates/services-infra-template.yaml
infra/bicep-generic/cdn/application-domain.main.bicep
infra/services/adp/portal/application-domain-custom-envs.yaml

Change the service connection back to ADP.
Relates to ADO Work Item [AB#296203](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/296203)
N/A
N/A

Change the service connection from SEC to ADP.

---

infra/services/coreai/core-ai-techradar/application-domain.main.bicepparam
infra/services/coreai/deploy-services-infra.yaml

Adding a domain for new mcu service.
Story number: #308026
n/a

Add core-ai-techradar with domain resource

---

infra/services/ffc/deploy-services-infra.yaml
infra/services/ffc/ffc-sfd-landing-page/application-domain.main.bicepparam

Add an endpoint for the SFD landing page service on front door.
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
N/A
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=490442&view=results

326112: Add SFD landing page service to front door.

---

infra/services/ffc/deploy-services-infra.yaml
infra/services/ffc/ffc-sfd-messages-processor/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-messages/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-permissions/application-domain.main.bicepparam

Add endpoint for the SFD messages, message processor and permissions.
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)

326112: Add frontdoor endpoints for the SFD services.

---

infra/services/ffc/deploy-services-infra.yaml
infra/services/ffc/ffc-sfd-ahwp-stub/application-domain.main.bicepparam

Correct the front door domains for SFD.
Relates to ADO Work Item [AB#326112](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/326112)
N/A
N/A

Correct the SFD domains.

---

infra/services/adp/portal/application-domain-custom-envs.yaml

[AB#304334](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/304334) (work item number in Azure DevOps). 
Fix Job Validation Error
- [ x ] Story Work items associated (not Tasks)
- [ x ] Successful testing run(s) link provided
- [ x ] Title pattern should be `{work item number}: {title}`
- [ x ] Description covers all the changes in the PR

304334: Container app improvement

---

infra/services/adp/portal/application-domain.main.bicepparam

[AB#344253](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/344253) 
update forwarding Protocol type
- [x ] Story Work items associated (not Tasks)
- [ x] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}`
- [x ] Description covers all the changes in the PR

344253: update forwarding Protocol type

---

infra/services/adp/portal/application-domain-custom-envs.yaml

[AB#249199](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/249199)
Setting up the PRD environment in Defra tenant
prd environment included in the pipeline

249199: Deploy Backstage Infrastructure using CI/CD Pipelines (SSV5)

---

infra/services/adp/portal/application-domain-custom-envs.yaml

[AB#259852](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259852)
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

259852 : disable prod env deployment

---

infra/services/coreai/coreai-mcu-frontend/application-domain.main.bicepparam
infra/services/coreai/deploy-services-infra.yaml

Added IaC files for adding a domain for the coreai-mcu-frontend service.
Relates to ADO Work Item [AB#356151](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/356151)

356151: Added infra for coreai-mcu-frontend service domain

---

infra/services/adp/portal/application-domain-custom-envs.yaml

Update the resource group and resource names for shared environments (DEV, TST, PRE, PRD) in the SSV subscription to include the environment names.
So that it is easier to understand which resources belong to which environment
* Uncomment SND1 environment
[AB#355292](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/355292)
Tested changes in Dev and verified Portal works with renames resources by other members of the team.
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

355292: Rename ssv shared env resources

---

infra/services/adp/portal/application-domain-custom-envs.yaml

Enabled PRD environment for portal domain deployment. 
[AB#259852](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259852)

259852:Enable PRD environment for Portal domain

---

infra/services/lap/deploy-services-infra.yaml
infra/services/lap/rpa-mit-manual-templates/application-domain.main.bicepparam

Added configuration for frontend domain: e.g: Relates to ADO Work Item [AB#387429](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/387429).

387429: Added configuration for rpa-mit-manual-templates frontend

---

.azuredevops/templates/services-infra-template.yaml

Use latest ADP pipeline version
[AB#334259](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/334259)

Services to snd4

---

.azuredevops/templates/services-infra-template.yaml
infra/bicep-generic/cdn/application-domain.main.bicep
infra/services/adp/portal/application-domain.main.bicepparam

[AB#399191](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399191)
Parameterized hostname for portal to get hostname for env file
Depends on PR: https://github.com/DEFRA/adp-pipeline-common/pull/223
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=588967&view=results

399191: Portal web hostname for ADP Portal

---

.azuredevops/templates/services-infra-template.yaml
infra/bicep-generic/cdn/application-domain.main.bicep
infra/services/adp/portal/application-domain.main.bicepparam

*Link to the relevant work items:*
[AB#399191](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399191)
Portal environment specific dns zone value added to param
Depends on PR:  https://github.com/DEFRA/adp-pipeline-common/pull/224
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=589367&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

399191: set dns zone to create records for portal

---

infra/bicep-generic/cdn/.bicep/customdomain/main.bicep
infra/bicep-generic/cdn/application-domain.main.bicep

[AB#399191](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399191) 
Added DNS zone scope based on the condition
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=589558&view=results

399191: DNS zone scope

---

.azuredevops/templates/generic-template.yaml
.azuredevops/templates/services-infra-template.yaml
infra/services/adp/ado-callback-api/application-domain-custom-envs.yaml
infra/services/adp/portal/application-domain-custom-envs.yaml
infra/services/ffc/deploy-services-infra.yaml
infra/services/ffc/ffc-sfd-ingress/application-domain.main.bicepparam

Correct the master ingress for SFD
N/A
N/A

Correct the master ingress for SFD

---

.azuredevops/templates/generic-template.yaml
.azuredevops/templates/services-infra-template.yaml
infra/bicep-generic/cdn/application-domain.main.bicep
infra/scripts/Set-AFDSecurityPolicy.ps1
infra/services/adp/ado-callback-api/application-domain-custom-envs.yaml
infra/services/adp/ado-callback-api/application-domain.main.bicepparam
infra/services/adp/deploy-services-infra.yaml
infra/services/adp/portal/application-domain-custom-envs.yaml
infra/services/adp/portal/application-domain.main.bicepparam
infra/services/coreai/core-ai-techradar/application-domain.main.bicepparam
infra/services/coreai/coreai-mcu-frontend/application-domain.main.bicepparam
infra/services/coreai/deploy-services-infra.yaml
infra/services/coreai/mcu-techspike-ai-web/application-domain.main.bicepparam
infra/services/eutd/deploy-services-infra.yaml
infra/services/eutd/trade-exports-packinglistai-ui/application-domain.main.bicepparam
infra/services/ffc/deploy-services-infra.yaml
infra/services/ffc/ea-wq-incident-web/application-domain.main.bicepparam
infra/services/ffc/fcp-data-access-layer-api/application-domain.main.bicepparam
infra/services/ffc/fcp-find-ai-frontend/application-domain.main.bicepparam
infra/services/ffc/ffc-demo-payment-web/application-domain.main.bicepparam
infra/services/ffc/ffc-demo-web/application-domain.main.bicepparam
infra/services/ffc/ffc-ffd-frontend-poc/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-ahwp-stub/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-business/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-landing-page/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-messages/application-domain.main.bicepparam
infra/services/ffc/ffc-sfd-permissions/application-domain.main.bicepparam
infra/services/lap/deploy-services-infra.yaml
infra/services/lap/rpa-mit-manual-templates/application-domain.main.bicepparam
infra/services/lap/rpa-mit-web/application-domain.main.bicepparam

[AB#392627](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/392627)
This custom rule will restrict accessing the service form specific  countries 
A new WAF (external) and Geographical restriction custom rule created
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=591229&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=590550&view=results

392627:Implement Geographical Restrictions on AFD WAF

---

infra/services/ffc/fcp-data-access-layer-api/aad-group.json

*Link to the relevant work items:*
[AB#399652](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399652)
Updated the group name as per the service name

399652: Updated group name

---

.azuredevops/templates/services-infra-template.yaml

[AB#407772](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/407772)
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

407772: Renamed service connection

---

infra/services/ffc/fcp-data-access-layer-api/app-registration.json

*Link to the relevant work items:*
[AB#399652](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/399652)
Updated the keyvault name to store the app reg secrets
Depends on PR https://github.com/DEFRA/adp-infrastructure-core/pull/218
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=604445&view=results

399652: Point to public keyvault

---

.azuredevops/templates/services-infra-template.yaml

[AB#405056](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/405056) 
Depends on following PRs
1. https://github.com/DEFRA/adp-common-scripts/pull/2
2. https://github.com/DEFRA/adp-pipeline-common/pull/239
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=607539&view=results

405056: Use of common scripts

---

.azuredevops/templates/services-infra-template.yaml
infra/scripts/Add-MI-To-EntraGroup.ps1

Handle group and mi not exists scenario. 

Add MI to Entra Group

---

infra/scripts/Add-MI-To-EntraGroup.ps1

Added a conditions to check the member count to prevent error when the are members to add.

Add condition to check members

---

infra/services/coreai/coreai-mcu-frontend/app-registration.json

[AB#418648](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/418648)
removed not available param lang and created app in snd4
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=627876&view=results

418648: removed not available param lang

---

infra/bicep-generic/service-bus/.bicep/topic/main.bicep
infra/bicep-generic/service-bus/service-bus-entities-rbac.main.bicep
infra/scripts/Get-ServicePrincipal.ps1
infra/services/eutd/external-services-adp-servicebus-access.yaml
infra/services/eutd/external-services/env-vars/dev1.yaml
infra/services/eutd/external-services/env-vars/prd1.yaml
infra/services/eutd/external-services/env-vars/pre1.yaml
infra/services/eutd/external-services/env-vars/snd4.yaml
infra/services/eutd/external-services/env-vars/tst1.yaml
infra/services/eutd/external-services/service-bus-entities-rbac.main.bicepparam

Added a pipeline to give access to external services.
[AB#417340](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/417340)

417340: Eutd external services sb access

---

infra/services/coreai/coreai-mcu-frontend/app-registration.json

[AB#418648](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/418648)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=630959&view=results

418648: appreg additonal api permissions

---

infra/services/ffc/fcp-data-access-layer-api/aad-group.json

<[AB#433792](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/433792)>
Add new AD group for DAL, so they can restrict access from Power Apps
SND4 has all worked: https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=662665&view=results

433792: Add AD Group for DAL CRM

---

infra/services/lap/deploy-services-infra.yaml
infra/services/lap/rpa-mit-manual-templates/app-registration.json

Creating an App Registration for MIT Manual Template Frontend
[AB#440102](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/440102)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=678235&view=results

AB440102: Creating App Registration for MIT Manual Templates

---

infra/services/lap/rpa-mit-manual-templates/app-registration.json

[AB#440102](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/440102)
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=682537&view=results

AB440102: Adding app registration for MIT Templates Backend service

---

infra/services/ffc/fcp-data-access-layer-api/aad-group.json

Adding David Aitch as owner for DAL group.

Adding David Aitch as owner
